<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Anggota_model extends CI_Model
{

    public $table = 'anggota';
    public $id = 'id_anggota';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('a.*,b.*');
        $this->db->from('anggota a');
        $this->db->join('wilayah b', 'a.id_wilayah = b.id_wilayah');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function join_wilayah_anggota()
    {
        $this->db->select('a.*,b.*');
        $this->db->from('wilayah a');
        $this->db->join('anggota b', 'a.id_wilayah = b.id_wilayah');
        return $this->db->get()->result();
    }

}

/* End of file Anggota_model.php */
/* Location: ./application/models/Anggota_model.php */
/* Please DO NOT modify this information : */
/* Generated by CRUDV2 Generator For AdminLTE Template 2018-12-18 05:04:18 */