<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Kader_model extends CI_Model
{

    public $table = 'kader';
    public $id = 'id_kader';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('a.*, b.nik, b.nama_anggota');
        $this->db->from('kader a');
        $this->db->join('anggota b', 'a.id_anggota = b.id_anggota');
        $this->db->where('a.status_kader', 'aktif');
        $this->db->order_by('id_kader', 'DESC');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) 
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function nonaktif($id)
    {
        $this->db->where($this->id, $id);
        $this->db->update('kader', array('status_kader' => 'nonaktif'));
    }

}

/* End of file Kader_model.php */
/* Location: ./application/models/Kader_model.php */
/* Please DO NOT modify this information : */
/* Generated by CRUDV2 Generator For AdminLTE Template 2019-06-03 08:11:00 */